version: '3.8'

services:
  python_script:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: minhasenha
      POSTGRES_USER: postgres
      POSTGRES_DB: my_database
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
